source 'https://github.com/alejandroCastillo7768/MobilePodspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/facebook/react-native.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

use_frameworks!
target 'MyLib_Tests' do
  pod 'MyLib', :path => '../'

  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

end


#require_relative '../node_modules/react-native/scripts/react_native_pods'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#
#source 'https://github.com/alejandroCastillo7768/MobilePodspecs.git'
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/facebook/react-native.git'
#
#platform :ios, '13.0'
#
#target 'MyLib_Tests' do
#
#  pod 'MyLib', :path => '../'
#
#  config = use_native_modules!
#
#  use_react_native!(
#    :path => config[:reactNativePath],
#    # to enable hermes on iOS, change `false` to `true` and then install pods
#    :hermes_enabled => false
#  )
#
#  # Enables Flipper.
#  #
#  # Note that if you have use_frameworks! enabled, Flipper will not work and
#  # you should disable the next line.
#  use_flipper!()
#
#  post_install do |installer|
#    react_native_post_install(installer)
#  end
#end
